create table if not exists public.audit_logs (
  id_audit bigint generated by default as identity primary key,
  tabla text not null,
  accion text not null,
  registro_id text,
  usuario_id uuid,
  datos_anteriores jsonb,
  datos_nuevos jsonb,
  creado timestamptz not null default now()
);

alter table public.audit_logs enable row level security;

drop policy if exists "Admins can read audit logs"
on public.audit_logs;

create policy "Admins can read audit logs"
on public.audit_logs
for select
to authenticated
using (public.is_admin(auth.uid()));

create or replace function public.fn_audit_productos()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.audit_logs (
      tabla,
      accion,
      registro_id,
      usuario_id,
      datos_nuevos
    )
    values (
      'productos',
      tg_op,
      new.id_producto::text,
      auth.uid(),
      to_jsonb(new)
    );

    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.audit_logs (
      tabla,
      accion,
      registro_id,
      usuario_id,
      datos_anteriores,
      datos_nuevos
    )
    values (
      'productos',
      tg_op,
      new.id_producto::text,
      auth.uid(),
      to_jsonb(old),
      to_jsonb(new)
    );

    return new;
  elsif tg_op = 'DELETE' then
    insert into public.audit_logs (
      tabla,
      accion,
      registro_id,
      usuario_id,
      datos_anteriores
    )
    values (
      'productos',
      tg_op,
      old.id_producto::text,
      auth.uid(),
      to_jsonb(old)
    );

    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_audit_productos
on public.productos;

create trigger trg_audit_productos
after insert or update or delete
on public.productos
for each row
execute function public.fn_audit_productos();